### ISSUE TITLE
Closing the .cia game.

### ISSUE THREAD

**Issue by Slashin-it-up** [DDews/Snakes#1]
If you close the game, the screen will be running however it wont get passed the. closing software popup.

**Comment by DDews** [comment]
how are you closing the game? home button or pressing start?

**Comment by DDews** [comment]
I'm currently refactoring and there won't be a .cia version of the game for a while. When I do make a .cia I will make sure this doesn't happen

**Comment by DDews** [comment]
I found the problem and plan to patch it for next version release

**Comment by DDews** [comment]
This issue has been fixed.
